auditlog added to enterprise folder
Healthlane-Technologies/Zango pull request #157
Opened 2024-03-18 02:40 UTC by deepakdinesh1123

2024-04-03 12:19 UTC, shahharsh176 commented on backend/src/zelthy/api/platform/tenancy/v1/urls.py
> +from zelthy.api.platform.audit.v1 import urls as audit_v1_urls
`audit` can be changed to `auditlog`

2024-04-03 12:24 UTC, shahharsh176 commented on backend/src/zelthy/api/platform/tenancy/v1/urls.py
> +    re_path(r"^(?P<app_uuid>[\w-]+)/audit/", include(audit_v1_urls)),
`auditlog`

2024-04-04 04:51 UTC, shahharsh176 requested changes

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/apps/auditlog/__init__.py
> +# __version__ = version("django-auditlog")
if this is not need needed pls remove the commented code

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/apps/auditlog/models.py
> +        on_delete=models.DO_NOTHING,
we can change the on_delete to `models.SET_NULL`

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/apps/auditlog/models.py
> +        on_delete=models.DO_NOTHING,
change the on_delete to `models.SET_NULL`

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/apps/auditlog/models.py
> +                obj = ObjectStore.objects.get(object_uuid=instance.object_uuid)
also handle the case where objectstore doesn't contain the object with given `instance.object_uuid`, in this case code shouldn't break, object_ref can be None in that case

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/apps/exportjob/models.py
> +from django.db import models
please remove the exportjob as of now

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/config/urls_public.py
> +    # urlpatterns += [
pls revert this change

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/config/urls_tenants.py
> +    # path("__debug__/", include("debug_toolbar.urls")),
pls revert this change

2024-04-04 04:51 UTC, shahharsh176 commented on backend/src/zelthy/config/urls_tenants.py
> +    # urlpatterns += [
pls revert this change

2024-04-12 09:50 UTC, shahharsh176 commented
@deepakdinesh1123 should we change "api/platform/auditlog" folder to `api/platform/auditlogs` to be in sync with app name `auditlogs`

2024-05-03 10:05 UTC, kc-diabeat commented on frontend/src/pages/app/components/Layout/SideMenu.jsx
> +			{/* <NavLink
Pls remove unnecessary commented code

2024-05-03 10:07 UTC, kc-diabeat commented on frontend/src/pages/appAccessLogs/slice/index.js
> +export const appAccessLogsSlice = createSlice({
Accesslog related code should not be included in this PR.

2024-05-03 10:32 UTC, kc-diabeat commented on backend/src/zelthy/apps/auditlogs/LICENSE
> +The MIT License (MIT)
Lets have a readme file in this folder where we detail out:
- which version of auditlog library we have taken
- what changes have we made
- overall rationale
- How is it being used, how to exclude model, fields, etc.
Also include a section in Docs

2024-06-27 05:49 UTC, closed without merging