accesslogs added
Healthlane-Technologies/Zango pull request #285
Opened 2024-07-09 12:01 UTC by deepakdinesh1123

2024-07-11 04:22 UTC, shahharsh176 requested changes

2024-07-11 04:22 UTC, shahharsh176 commented on backend/src/zango/apps/accesslogs/utils.py
> +        if "@" in username and "." in username:
can we detect whether the username is email or not by email regex ?

2024-07-16 16:20 UTC, kc-diabeat approved these changes

2024-07-16 16:21 UTC, kc-diabeat approved these changes

2024-07-16 18:36 UTC, shahharsh176 approved these changes

2024-07-16 19:05 UTC, merged