zango release workflow added
Healthlane-Technologies/Zango pull request #301
Opened 2024-07-24 12:35 UTC by deepakdinesh1123

2024-07-24 13:02 UTC, shahharsh176 requested changes

2024-07-24 13:04 UTC, deepakdinesh1123 commented on backend/MANIFEST.in
> +include requirements/base.txt
I was getting in an error saying requirements/base.txt not found when trying to build the package so I added this

2024-07-24 13:31 UTC, shahharsh176 commented on backend/MANIFEST.in
> +include requirements/base.txt
oh ok, I was using `python3 setup.py bdist_wheel sdist` in that it was not coming

2024-07-25 13:51 UTC, shahharsh176 approved these changes

2024-07-25 14:09 UTC, kc-diabeat approved these changes

2024-07-25 14:09 UTC, merged