Cypress/e2e tests
Healthlane-Technologies/Zango pull request #337
Opened 2024-08-03 11:27 UTC by madhu-355

2024-08-03 11:29 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10227639105). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-03 11:48 UTC, shahharsh176 requested changes

2024-08-03 11:48 UTC, shahharsh176 commented on .github/workflows/e2e-cypress-tests.yml
> +      - cypress/e2e-tests
change branch to main

2024-08-03 11:48 UTC, shahharsh176 commented on .github/workflows/e2e-cypress-tests.yml
> +    # paths:
paths will be 

- frontend
- e2e-tests

2024-08-03 11:48 UTC, shahharsh176 commented on .github/workflows/e2e-cypress-tests.yml
> +    # paths:
```
workflow_run:
    workflows: [Push build to Main]
    types:
      - completed
 ```

2024-08-03 11:48 UTC, shahharsh176 commented on frontend/package.json
> +		"uglifyjs-webpack-plugin": "^1.1.2",
revert this change

2024-08-03 11:48 UTC, shahharsh176 commented on frontend/yarn.lock
> -ajv-errors@^1.0.0:
revert changes of this file

2024-08-03 12:33 UTC, kc-diabeat commented on e2e-tests/cucumber-html-report.js
> +  metadata: {
@madhu-355 I think metadata (e.g. browser device, platform) should be set from the environment and not hardcoded.

2024-08-03 12:33 UTC, kc-diabeat commented on e2e-tests/cucumber-html-report.js
> +      { label: "Project", value: "Zango e2e-Tests Report" },
We should explore the possibility of showing Zango version as well @madhu-355

2024-08-03 12:33 UTC, kc-diabeat commented on frontend/src/metadata.json
> +{"buildMajor":2,"buildMinor":0,"buildPatch":7,"buildTag":""}
whats the rationale behind this version jump? @madhu-355 @shahharsh176

2024-08-03 14:35 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10228771383). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-03 14:38 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10228784835). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-04 07:02 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10234288863). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-04 07:51 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10234564660). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-04 08:50 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10234914845). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-05 05:07 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10242919389). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-05 05:09 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10242939023). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-05 05:17 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10243014035). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-05 05:19 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10243035293). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-05 05:37 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10243223885). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 09:06 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10263581170). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 09:47 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264190945). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 09:52 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264270946). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 09:54 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264298863). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 10:02 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264400013). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 10:03 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264423776). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 10:06 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264464166). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 10:08 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264497348). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-06 10:17 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10264636911). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-07 09:20 UTC, closed without merging