country code selection dropdown for phone number added
Healthlane-Technologies/Zango pull request #362
Opened 2024-08-14 12:13 UTC by deepakdinesh1123

2024-08-15 05:51 UTC, shahharsh176 requested changes

2024-08-15 05:51 UTC, shahharsh176 commented on backend/src/zango/core/utils.py
> +def validate_phone(phone_number):
```python
def validate_phone(phone_number, region=None):
    try:
        region = region or settings.PHONENUMBER_DEFAULT_REGION
        phone_number = phonenumbers.parse(phone_number, region=region)
        if phonenumbers.is_valid_number(phone_number):
            return True
    except:
        return False
```

Also, can you add arguments info in docstring  ?

2024-08-19 04:44 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10447285227). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-30 11:50 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10632129530). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-30 11:53 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10632170174). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-03 10:57 UTC, shahharsh176 requested changes

2024-09-03 10:57 UTC, shahharsh176 commented on backend/src/zango/assets/app_panel/js/build.1723136204750.min.js
@adhiraj23zelthy Please remove the build

2024-09-03 10:57 UTC, shahharsh176 commented on backend/src/zango/assets/js/jquery/3.7.1/jquery.min.js
Is there any changes done in this file?
if not then we can revert this

2024-09-03 10:57 UTC, shahharsh176 commented on frontend/src/metadata.json
> +{"buildMajor":0,"buildMinor":3,"buildPatch":1,"buildTag":""}
please revert changes in this file

2024-09-03 11:51 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10682322935). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-03 13:33 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10683982167). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-04 09:59 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10699381300). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-11 20:43 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10819353602). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-13 12:54 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10849465233). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-17 12:33 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10903088750). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-25 09:20 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/11030074739). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-25 11:02 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/11031653026). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-25 12:56 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/11033447115). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-25 13:18 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/11033832260). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-25 13:18 UTC, shahharsh176 approved these changes

2024-09-25 13:31 UTC, merged