Feat/fe task detail and history
Healthlane-Technologies/Zango pull request #364
Opened 2024-08-20 06:17 UTC by prem056627

Added : new menu item "releases"

2024-08-20 06:19 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10466327644). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-20 06:38 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10466549643). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-20 06:51 UTC, sukuna28 requested changes

2024-08-20 06:51 UTC, sukuna28 commented on frontend/src/pages/appPoliciesManagement/components/AppTable/RowMenu.jsx
> -						</Menu.Item> */}
@prem056627 can you pls remove this commented code?

2024-08-20 06:51 UTC, sukuna28 commented on frontend/src/pages/appReleasesRoutes/routes/Index.jsx
> +// import AppLogs from '../components/AppLogs.jsx';
@prem056627 remove unused imports

2024-08-20 06:51 UTC, sukuna28 commented on frontend/src/pages/appPackagesManagement/components/AppTable/RowMenu.jsx
> -											</span> */}
@prem056627 remove commnets

2024-08-20 06:51 UTC, sukuna28 commented on frontend/src/pages/app/routes/index.js
> +// import { AppLogsRoutes } from '../../appReleasesRoutes/components/appLogs/Index'
@prem056627 remove unused import

2024-08-20 06:51 UTC, sukuna28 commented on frontend/src/mocks/appTasksManagementHandlers.js
> +	}),
@prem056627 revert this data as previously discussed

2024-08-20 06:51 UTC, sukuna28 commented on frontend/src/mocks/appReleasesHandlers.js
> +
@prem056627 remove commented code

2024-08-20 06:51 UTC, sukuna28 commented on backend/src/zango/assets/app_panel/js/build.1723531926721.min.js.LICENSE.txt
@prem056627 remove this file

2024-08-20 09:10 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10468662927). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-20 10:01 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10469415457). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-21 04:26 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10483477013). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-21 04:40 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10483605159). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-08-21 04:49 UTC, sukuna28 requested changes

2024-09-03 12:30 UTC, shahharsh176 requested changes

2024-09-03 12:30 UTC, shahharsh176 commented on backend/src/zango/assets/app_panel/js/build.1723531926721.min.js.LICENSE.txt
remove this file

2024-09-03 12:30 UTC, shahharsh176 commented on frontend/src/metadata.json
> +{"buildMajor":0,"buildMinor":3,"buildPatch":1,"buildTag":""}
revert changes in this file

2024-09-04 06:49 UTC, kc-diabeat commented
The build artifact is available in the artifact section [here](https://github.com/Healthlane-Technologies/Zango/actions/runs/10696533749). You can download it and place the build file under backend/src/zango/assets/app_panel/js for local testing and verification.

2024-09-04 07:14 UTC, shahharsh176 requested changes

2024-09-04 07:14 UTC, shahharsh176 commented on backend/src/zango/assets/app_panel/js/build.1723531926721.min.js.LICENSE.txt
@prem056627 Please remove this file

2024-09-04 12:28 UTC, closed without merging